version: "3"
services:
  django:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - "postgres"
    volumes:
      - ./docker_volumes/audio_files:/home/MP3API/audio_files
      - ./docker_volumes/logs:/home/MP3API/logs
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: djangouser
      POSTGRES_PASSWORD: obo696
      POSTGRES_DB: djangodb
    volumes:
      - ./docker_volumes/postgres-data:/var/lib/postgresql/data 