# Generated by Django 4.0.4 on 2022-05-11 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('audio_file', models.FileField(blank=True, editable=False, upload_to='audio_files/')),
                ('sentiment_positive', models.FloatField(blank=True, default=0, editable=False)),
                ('sentiment_negative', models.FloatField(blank=True, default=0, editable=False)),
                ('sentiment_neutral', models.FloatField(blank=True, default=0, editable=False)),
                ('transcript', models.TextField(blank=True, default='', editable=False)),
                ('words', models.TextField(blank=True, default='')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MP3 Recording',
                'verbose_name_plural': 'MP3 Recordings',
            },
        ),
    ]
