# Generated by Django 4.0.4 on 2022-05-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0002_remove_recording_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='file',
            field=models.FileField(blank=True, upload_to='audio_files/'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='transcript',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
