# Generated by Django 4.0.4 on 2022-05-10 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0003_recording_file_alter_recording_transcript'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recording',
            old_name='file',
            new_name='audio_file',
        ),
    ]
