# Generated by Django 4.0.4 on 2022-05-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0004_rename_file_recording_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='sentiment_negative',
            field=models.FloatField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='recording',
            name='sentiment_neutral',
            field=models.FloatField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='recording',
            name='sentiment_positive',
            field=models.FloatField(blank=True, default=0, editable=False),
        ),
    ]
