# Generated by Django 4.0.4 on 2022-05-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0005_recording_sentiment_negative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='words',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='recording',
            name='audio_file',
            field=models.FileField(blank=True, editable=False, upload_to='audio_files/'),
        ),
    ]
